pipeline:
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Taerk/TioConverter2
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Pull Latest AST-CLI
                  identifier: Pull_ASTCLI
                  spec:
                    shell: Sh
                    command: |-
                      wget https://github.com/Checkmarx/ast-cli/releases/latest/download/ast-cli_linux_x64.tar.gz && \
                        tar -zxvf ast-cli_linux_x64.tar.gz
              - step:
                  type: Run
                  name: Validate CxOne Authentication
                  identifier: Validate_CxOne_Authentication
                  spec:
                    connectorRef: account.harnessImage
                    image: checkmarx/ast-cli
                    shell: Sh
                    command: ./app/cx auth validate
              - step:
                  type: Run
                  name: Run Scan
                  identifier: Run_Scan
                  spec:
                    connectorRef: account.harnessImage
                    image: checkmarx/ast-cli
                    shell: Sh
                    command: |-
                      ./app/cx scan create \
                        --project-name "<+project.name>" \
                        --branch "<+pipeline.branch>" \
                        -s .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        variables:
          - name: CX_BASEURI
            type: String
            description: ""
            required: true
            value: https://ast.checkmarx.net/
          - name: CX_TENANT
            type: String
            description: ""
            required: true
            value: se_gabriel_nieves
          - name: CX_APIKEY
            type: Secret
            description: ""
            required: false
            value: CxOne_API_Key
  identifier: Build_Taerk_TioConverter2_1722013971782_Clone
  tags: {}
  name: Build TioConverter2 - Clone
