pipeline:
  identifier: Build_Taerk_TioConverter2_1722013971782
  name: Build TioConverter2
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Taerk/TioConverter2
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: ls
                  spec:
                    shell: Sh
                    command: ls
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Pull AST-CLI
                  identifier: Pull_ASTCLI
                  spec:
                    shell: Sh
                    command: docker pull checkmarx/ast-cli
              - step:
                  type: Run
                  name: Validate CxOne Authentication
                  identifier: Validate_CxOne_Authentication
                  spec:
                    shell: Sh
                    command: |-
                      docker run \
                        -e CX_APIKEY="$CX_APIKEY" \
                        -e CX_BASE_URI="$CX_BASE_URI" \
                        -e CX_TENANT="$CX_TENANT" \
                        checkmarx/ast-cli auth validate
              - step:
                  type: Run
                  name: Run Scan
                  identifier: Run_Scan
                  spec:
                    shell: Sh
                    command: |-
                      docker run \
                        -e CX_APIKEY="$CX_APIKEY" \
                        -e CX_BASE_URI="$CX_BASE_URI" \
                        -e CX_TENANT="$CX_TENANT" \
                        checkmarx/ast-cli scan create \
                        --project <+project.name> \
                        --branch <+pipeline.branch> \
                        -s .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
